app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

# Homepage
Route::get('/', array('uses' => 'HomeController@index', 'as' => 'home'));

#	User authentication
Route::get('login', array('uses'=>'HomeController@showLogin'));
Route::post('login', array('uses' => 'HomeController@doLogin'));
Route::get('logout', array('uses' => 'HomeController@doLogout'));

// Resources (RESTFUL)
Route::resource('customers', 'CustomersController');
Route::resource('projects', 'ProjectsController');
Route::resource('tasks', 'TasksController');
Route::resource('users', 'UsersController');
Route::resource('report', 'ReportController', array('only' => array('index', 'show')));

// Profile
Route::resource('profile', 'ProfileController', array('only' => array('edit', 'update')));

// Administrating routes, for admins only
Route::resource('admin/users', 'AdminUsersController');
Route::resource('admin/instances', 'AdminInstancesController');
Route::resource('admin/roles', 'AdminRolesController');
//Route::resource('admin/permissions', 'AdminPermissionsController');

//Route::resource('work_records', 'WorkRecordsController');
// Let's create an ALIAS route "track" which displays the main GUI for tracking time
// The CRUD of WorkRecord objects is mostly done over AJAX
Route::get('track/{date?}', array('as' => 'track.index', 'uses' => 'WorkRecordsController@index'));
Route::post('track/store', array('as' => 'track.store', 'uses' => 'WorkRecordsController@store'));
Route::post('track/update/{id}', array('as' => 'track.update', 'uses' => 'WorkRecordsController@update'));
Route::post('track/start/{id}', array('as' => 'track.start', 'uses' => 'WorkRecordsController@start'));
Route::post('track/stop/{id}', array('as' => 'track.stop', 'uses' => 'WorkRecordsController@stop'));
Route::get('track/get_accurate_time/{id}', array('as' => 'track.accurate_time', 'uses' => 'WorkRecordsController@getAccurateTime'));
Route::post('track/delete/{id}', array('as' => 'track.delete', 'uses' => 'WorkRecordsController@delete'));


// Report Controller
//Route::get('report/{project_id?}', array('as' => 'report.show_project', 'uses' => 'ReportController@show_project'));

app/controllers/AdminInstancesController.php
<?php

class AdminInstancesController extends \BaseController
{


    public function __construct()
    {
        parent::__construct();
        
        $this->beforeFilter(function () {
            if ( ! $this->user->hasPermission('administrate_instances')) {
                App::abort(403);
            }
        });
    }


    /**
     * Display a listing of users
     *
     * @return Response
     */
    public function index()
    {
        $instances = Instance::all();

        return View::make('admin_instances.index', compact('instances'));
    }


    /**
     * Show the form for creating a new user
     *
     * @return Response
     */
    public function create()
    {
        return View::make('admin_instances.create');
    }


    /**
     * Store a newly created user in storage.
     *
     * @return Response
     */
    public function store()
    {
        try {
            Instance::create(Input::all());
        } catch (ValidationException $e) {
            return Redirect::back()->withInput(Input::all())->withErrors($e->getErrors());
        }

        return Redirect::route('admin.instances.index')->with('success', 'Successfully created Instance ' . Input::get('title'));

    }


    /**
     * Display the specified instance.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        $user = Instance::findOrFail($id);

        return View::make('admin_instances.show', compact('instance'));
    }


    /**
     * Show the form for editing the specified user.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $instance = Instance::findOrFail($id);

        return View::make('admin_instances.edit', compact('instance'));
    }


    /**
     * Update the specified user in storage.
     *
     * @param  int $id
     * @return Response
     */
    public function update($id)
    {
        $instance = Instance::findOrFail($id);
        try {
            $instance->update(Input::all());
        } catch (ValidationException $e) {
            return Redirect::back()->withInput(Input::all())->withErrors($e->getErrors());
        }

        return Redirect::route('admin.instances.index')->with('success', 'Successfully updated Instance ' . Input::get('title'));

    }


    /**
     * Remove the specified user from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        Instance::destroy($id);

        return Redirect::route('admin_instances.index');
    }

}

app/views/admin_instances/_form.blade.php
<div class="two fields">
    <div class="field @if($errors->has('title')) error @endif">
        {{ Form::label('title', 'Company', array('class' => 'ui label')) }}
        <div class="ui left labeled input">
            {{ Form::text('title') }}
            <div class="ui corner label">
                <i class="icon asterisk"></i>
            </div>
        </div>
    </div>
    <div class="field">
        {{ Form::label('street', 'Street', array('class' => 'ui label')) }}
        <div class="ui left labeled input">
            {{ Form::text('street') }}
        </div>
    </div>
</div>
<div class="two fields">
    <div class="field">
        {{ Form::label('zip', 'ZIP', array('class' => 'ui label')) }}
        <div class="ui left labeled input">
            {{ Form::text('zip') }}
        </div>
    </div>
    <div class="field">
        {{ Form::label('city', 'City', array('class' => 'ui label')) }}
        <div class="ui left labeled input">
            {{ Form::text('city') }}
        </div>
    </div>
</div>
<div class="two fields">
    <div class="field">
        {{ Form::label('tel', 'Phone', array('class' => 'ui label')) }}
        <div class="ui left labeled input">
            {{ Form::text('tel') }}
        </div>
    </div>
    <div class="field">
        {{ Form::label('fax', 'Fax', array('class' => 'ui label')) }}
        <div class="ui left labeled input">
            {{ Form::text('fax') }}
        </div>
    </div>
</div>
<div class="field @if($errors->has('email')) error @endif">
    {{ Form::label('email', 'E-Mail', array('class' => 'ui label')) }}
    <div class="ui left labeled input">
        {{ Form::email('email') }}
        <div class="ui corner label">
            <i class="icon asterisk"></i>
        </div>
    </div>
</div>

app/views/admin_instances/create.blade.php
@extends('layouts.default')
@section('content')
<div class="sixteen wide column">

    <h1 class="ui header">Create Instance</h1>

    <div class="ui form segment">
        {{ Form::open(array('route' => array('admin.instances.store'))) }}
        @include('admin_instances._form')
        <button class="ui teal submit primary button">Create</button>
        {{ Form::close() }}
    </div>
</div>
@stop

app/views/admin_instances/edit.blade.php
@extends('layouts.default')
@section('content')
<div class="sixteen wide column">

    <h1 class="ui header">Edit Instance</h1>

    <div class="ui form segment">
        {{ Form::model($instance, array('method' => 'PUT', 'route' => array('admin.instances.update', $instance->id))) }}
        @include('admin_instances._form')
        <button class="ui teal submit primary button">Update</button>
        {{ Form::close() }}
    </div>

</div>
@stop

app/views/admin_instances/index.blade.php
@extends('layouts.default')
@section('content')
<div class="sixteen wide column">
<h1 class="ui header">Instances</h1>
    <table class="ui sortable table segment">
        <thead>
            <tr>
                <th class="ascending">Company</th>
                <th>Street</th>
                <th>ZIP</th>
                <th>City</th>
                <th>Phone</th>
                <th>E-Mail</th>
                <th class="actions">Actions</th>
            </tr>
        </thead>
        <tbody>
        @foreach($instances as $instance)
            <tr>
                <td>{{ $instance->title }}</td>
                <td>{{ $instance->street }}</td>
                <td>{{ $instance->zip }}</td>
                <td>{{ $instance->city }}</td>
                <td>{{ $instance->tel }}</td>
                <td>{{ $instance->email }}</td>
                <td class="actions">
                    <a href="{{ route('admin.instances.edit', array($instance->id)) }}" class="ui mini icon button"><i class="icon edit"></i></a>
                    {{--<a href="#" class="ui mini icon button red"><i class="icon trash"></i></a>--}}
                </td>
            </tr>
        @endforeach
        </tbody>
        <tfoot>
        <tr>
            <th colspan="7">
                <a class="ui teal labeled icon mini button" href="{{ route('admin.instances.create') }}">
                    <i class="plus icon"></i>
                    Add Instance
                </a>
            </th>
        </tr>
        </tfoot>
    </table>
</div>
@stop