app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

# Homepage
Route::get('/', array('uses' => 'HomeController@index', 'as' => 'home'));

#	User authentication
Route::get('login', array('uses'=>'HomeController@showLogin'));
Route::post('login', array('uses' => 'HomeController@doLogin'));
Route::get('logout', array('uses' => 'HomeController@doLogout'));

// Resources (RESTFUL)
Route::resource('customers', 'CustomersController');
Route::resource('projects', 'ProjectsController');
Route::resource('tasks', 'TasksController');
Route::resource('users', 'UsersController');
Route::resource('report', 'ReportController', array('only' => array('index', 'show')));

// Profile
Route::resource('profile', 'ProfileController', array('only' => array('edit', 'update')));

// Administrating routes, for admins only
Route::resource('admin/users', 'AdminUsersController');
Route::resource('admin/instances', 'AdminInstancesController');
Route::resource('admin/roles', 'AdminRolesController');
//Route::resource('admin/permissions', 'AdminPermissionsController');

//Route::resource('work_records', 'WorkRecordsController');
// Let's create an ALIAS route "track" which displays the main GUI for tracking time
// The CRUD of WorkRecord objects is mostly done over AJAX
Route::get('track/{date?}', array('as' => 'track.index', 'uses' => 'WorkRecordsController@index'));
Route::post('track/store', array('as' => 'track.store', 'uses' => 'WorkRecordsController@store'));
Route::post('track/update/{id}', array('as' => 'track.update', 'uses' => 'WorkRecordsController@update'));
Route::post('track/start/{id}', array('as' => 'track.start', 'uses' => 'WorkRecordsController@start'));
Route::post('track/stop/{id}', array('as' => 'track.stop', 'uses' => 'WorkRecordsController@stop'));
Route::get('track/get_accurate_time/{id}', array('as' => 'track.accurate_time', 'uses' => 'WorkRecordsController@getAccurateTime'));
Route::post('track/delete/{id}', array('as' => 'track.delete', 'uses' => 'WorkRecordsController@delete'));


// Report Controller
//Route::get('report/{project_id?}', array('as' => 'report.show_project', 'uses' => 'ReportController@show_project'));

app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends Model implements UserInterface, RemindableInterface
{

    use UserTrait, RemindableTrait;


    /**
     * @var array
     */
    public static $create_rules = array(
        'username' => 'required|unique:users',
        'instance_id' => 'required',
        'password' => 'required|min:3|confirmed'
    );


    /**
     * @var array
     */
    public static $update_rules = array(
        'username' => 'required',
        'password' => 'sometimes|required|min:3|confirmed'
    );

    /**
     * The users role. 0 stands for no role / not logged in. The higher the role, the more rights the user has.
     */
    /*    private $role = 0;*/

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = array('password', 'remember_token');

    /**
     * @var array
     */
    protected $guarded = array('id', 'password_confirmation');

    /**
     * Holds the permissions for this user, cached
     *
     * @var array
     */
    protected $permissions;


    /**
     * When updating, adjust update rules: the username must be unique except for the id of the current user
     *
     * @param array $attributes
     * @return bool|int
     * @throws ValidationException
     */
    public function update(array $attributes = array())
    {
        static::$update_rules['username'] = 'required|unique:users,username,' . $this->id;
        static::validate($attributes, 'update');

        return parent::update($attributes);
    }


    /**
     * Get users of given instance
     *
     * @param $query
     * @param int|Instance $instance
     */
    public function scopeOfInstance($query, $instance)
    {
        $instance_id = ($instance instanceof Instance) ? $instance->id : $instance;

        return $query->where('instance_id', '=', $instance_id);
    }


    /**
     * Get Roles
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function roles()
    {
        return $this->belongsToMany('Role', 'role_users');
    }


    /**
     * Get Instance
     *
     * @return Instance
     */
    public function instance()
    {
        return $this->belongsTo('Instance');
    }


    /**
     * @param array $role_ids
     * @param bool $allow_system_roles
     */
    public function setRoles(array $role_ids=array(), $allow_system_roles = false)
    {
        $ids = $role_ids;
        if ( ! $allow_system_roles) {
            foreach ($role_ids as $role_id) {
                $role = Role::find($role_id);
                if ( ! $role->system) $ids[] = $role->id;
            }
        }

        $this->roles()->sync($ids);
    }


    /**
     * @param string $role_name Name of a role
     * @return bool
     */
    public function hasRole($role_name)
    {
        $role = $this->roles->filter(function ($role) use ($role_name) {
            return $role->name == $role_name;
        })->first();

        return ($role) ? true : false;
    }


    /**
     * Checks if the user has the given permission by a role
     *
     * @param string $permission_name Name of a permission
     * @return bool
     */
    public function hasPermission($permission_name)
    {
        $this->loadPermissions();

        return isset($this->permissions[$permission_name]);
    }


    /**
     * Setter for the password attribute
     *
     * @param string $password
     */
    public function setPasswordAttribute($password)
    {
        // Don't set empty passwords
        if ( ! $password) return;

        $this->attributes['password'] = Hash::make($password);
    }

    /**
     * Load all permissions from assigned roles
     */
    protected function loadPermissions()
    {
        if ( ! is_null($this->permissions)) {
            return;
        }

        $this->permissions = array();
        /** @var Role $role */
        foreach ($this->roles as $role) {
            $this->permissions = array_merge($this->permissions, $role->permissions->keyBy('name')->toArray());
        }
    }
}

app/controllers/UsersController.php
<?php

class UsersController extends \BaseController
{


    public function __construct()
    {
        parent::__construct();

        // Check for permission to manage users
        $this->beforeFilter(function () {
            if ( ! $this->user->hasPermission('manage_users')) {
                App::abort(403);
            }
        });
    }


    /**
     * Display a listing of users
     *
     * @return Response
     */
    public function index()
    {
        $users = User::ofInstance($this->user->instance)->orderBy('username')->get();

        return View::make('users.index', compact('users'));
    }


    /**
     * Show the form for creating a new user
     *
     * @return Response
     */
    public function create()
    {
        $roles = Role::instance()->get();

        return View::make('users.create', compact('roles'));
    }


    /**
     * Store a newly created user in storage.
     *
     * @return Response
     */
    public function store()
    {
        try {
            $user = User::create(array_merge(Input::except('roles'), array('instance_id' => $this->user->instance_id)));
            $user->setRoles(Input::get('roles'));
        } catch (ValidationException $e) {
            return Redirect::back()->withInput(Input::all())->withErrors($e->getErrors());
        }

        return Redirect::route('users.index')->with('success', 'Successfully created User ' . Input::get('username'));
    }


    /**
     * Display the specified user.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);

        $this->checkPermissionAndReturn($user);

        return View::make('users.show', compact('user'));
    }


    /**
     * Show the form for editing the specified user.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        $this->checkPermissionAndReturn($user);

        $roles = Role::instance()->get();

        return View::make('users.edit', compact('user', 'roles'));
    }


    /**
     * Update the specified user in storage.
     *
     * @param  int $id
     * @return Response
     */
    public function update($id)
    {
        $user = User::findOrFail($id);

        $this->checkPermissionAndReturn($user);

        try {
            $data = Input::except('roles');
            if ( ! $data['password']) unset($data['password']);
            $user->update($data);
            $user->setRoles(Input::get('roles'));
        } catch (ValidationException $e) {
            return Redirect::back()->withInput(Input::all())->withErrors($e->getErrors());
        }

        return Redirect::route('users.index')->with('success', 'Successfully updated User ' . Input::get('username'));
    }


    /**
     * Remove the specified user from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        User::destroy($id);

        return Redirect::route('users.index');
    }


    /**
     * Only the logged in user can modify his own project objects
     *
     * @param User $user
     */
    protected function checkPermissionAndReturn(User $user)
    {
        if ($user->instance_id != $this->user->instance_id) {
            App::abort(403);
        }
    }


}

app/views/users/_form.blade.php
<div class="one field">
    <div class="field @if($errors->has('username')) error @endif">
        {{ Form::label('username', 'Username', array('class' => 'ui label')) }}
        <div class="ui left labeled input">
            {{ Form::text('username') }}
            <div class="ui corner label">
                <i class="icon asterisk"></i>
            </div>
        </div>
    </div>

    <div class="field @if($errors->has('password')) error @endif">
        {{ Form::label('password', 'Password', array('class' => 'ui label')) }}
        <div class="ui left labeled password input">
            {{ Form::password('password') }}
            <div class="ui corner label">
                <i class="icon lock"></i>
            </div>
        </div>
    </div>

    <div class="field @if($errors->has('password_confirm')) error @endif">
        {{ Form::label('password_confirmation', 'Password Confirmation', array('class' => 'ui label')) }}
        <div class="ui left labeled password input">
            {{ Form::password('password_confirmation') }}
            <div class="ui corner label">
                <i class="icon lock"></i>
            </div>
        </div>
    </div>


    @if (isset($roles))
        <div class="field">
            {{ Form::label('roles', 'Roles', array('class' => 'ui label')) }}
            @foreach($roles as $role)
                <div class="field">
                    <div class="ui checkbox">
                        <input id="role_{{ $role->id }}" type="checkbox" name="roles[]" value="{{ $role->id }}"@if((isset($user) && $user->roles->contains($role)) || Input::get("roles.{$role->id}")) checked @endif>
                        <label for="role_{{ $role->id }}">{{ $role->title }}</label>
                    </div>
                </div>
            @endforeach
        </div>
    @endif

</div>

app/views/users/create.blade.php
@extends('layouts.default')
@section('content')
<div class="sixteen wide column">

    <h1 class="ui header">Create User</h1>

    <div class="ui form segment">
        {{ Form::open(array('route' => array('users.store'))) }}
        @include('users._form')
        <button class="ui teal submit primary button">Create</button>
        {{ Form::close() }}
    </div>
</div>
@stop

app/views/users/edit.blade.php
@extends('layouts.default')
@section('content')
<div class="sixteen wide column">

    <h1 class="ui header">Edit User Data</h1>

    <div class="ui form segment">
        {{ Form::model($user, array('method' => 'PUT', 'route' => array('users.update', $user->id))) }}
        @include('users._form')
        <button class="ui teal submit primary button">Update</button>
        {{ Form::close() }}
    </div>
</div>
@stop

app/views/users/index.blade.php
@extends('layouts.default')
@section('content')
<div class="sixteen wide column">
<h1 class="ui header">Users</h1>
    <table class="ui sortable table segment">
        <thead>
            <tr>
                <th class="ascending">Username</th>
                <th>Role(s)</th>
                <th class="actions">Actions</th>
            </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                <td>{{ $user->username }}</td>
                <td>{{ $user->roles->implode('title', ', ') }}</td>
                <td class="actions">
                    <a href="{{ route('users.edit', array($user->id)) }}" class="ui mini icon button"><i class="icon edit"></i></a>
                    {{--<a href="{{ route('users.destroy', array($user->id)) }}" class="ui mini button icon red"><i class="icon trash"></i></a>--}}
                </td>
            </tr>
        @endforeach
        </tbody>
        <tfoot>
        <tr>
            <th colspan="4">
                <a class="ui teal labeled icon mini button" href="{{ route('users.create') }}">
                    <i class="plus icon"></i>
                    Add User
                </a>
            </th>
        </tr>
        </tfoot>
    </table>
</div>
@stop

app/views/users/show.blade.php
/Applications/MAMP/htdocs/webeng-fs14/app/views/users/show.blade.php