app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

# Homepage
Route::get('/', array('uses' => 'HomeController@index', 'as' => 'home'));

#	User authentication
Route::get('login', array('uses'=>'HomeController@showLogin'));
Route::post('login', array('uses' => 'HomeController@doLogin'));
Route::get('logout', array('uses' => 'HomeController@doLogout'));

// Resources (RESTFUL)
Route::resource('customers', 'CustomersController');
Route::resource('projects', 'ProjectsController');
Route::resource('tasks', 'TasksController');
Route::resource('users', 'UsersController');
Route::resource('report', 'ReportController', array('only' => array('index', 'show')));

// Profile
Route::resource('profile', 'ProfileController', array('only' => array('edit', 'update')));

// Administrating routes, for admins only
Route::resource('admin/users', 'AdminUsersController');
Route::resource('admin/instances', 'AdminInstancesController');
Route::resource('admin/roles', 'AdminRolesController');
//Route::resource('admin/permissions', 'AdminPermissionsController');

//Route::resource('work_records', 'WorkRecordsController');
// Let's create an ALIAS route "track" which displays the main GUI for tracking time
// The CRUD of WorkRecord objects is mostly done over AJAX
Route::get('track/{date?}', array('as' => 'track.index', 'uses' => 'WorkRecordsController@index'));
Route::post('track/store', array('as' => 'track.store', 'uses' => 'WorkRecordsController@store'));
Route::post('track/update/{id}', array('as' => 'track.update', 'uses' => 'WorkRecordsController@update'));
Route::post('track/start/{id}', array('as' => 'track.start', 'uses' => 'WorkRecordsController@start'));
Route::post('track/stop/{id}', array('as' => 'track.stop', 'uses' => 'WorkRecordsController@stop'));
Route::get('track/get_accurate_time/{id}', array('as' => 'track.accurate_time', 'uses' => 'WorkRecordsController@getAccurateTime'));
Route::post('track/delete/{id}', array('as' => 'track.delete', 'uses' => 'WorkRecordsController@delete'));


// Report Controller
//Route::get('report/{project_id?}', array('as' => 'report.show_project', 'uses' => 'ReportController@show_project'));

app/controllers/AdminUsersController.php
<?php

class AdminUsersController extends \BaseController
{


    public function __construct()
    {
        parent::__construct();

        // Check for permission to administrate users
        $this->beforeFilter(function () {
            if ( ! $this->user->hasPermission('administrate_users')) {
                App::abort(403);
            }
        });
    }


    /**
     * Display a listing of users
     *
     * @return Response
     */
    public function index()
    {
        $users = User::all();

        return View::make('admin_users.index', compact('users'));
    }


    /**
     * Show the form for creating a new user
     *
     * @return Response
     */
    public function create()
    {
        $instances = Instance::all();
        $roles = $this->user->hasRole('superadmin') ? Role::all() : Role::instance()->get();

        return View::make('admin_users.create', compact('instances', 'roles'));
    }


    /**
     * Store a newly created user in storage.
     *
     * @return Response
     */
    public function store()
    {
        try {
            $data = Input::except('roles');
            if ( ! $data['password']) unset($data['password']);
            $user = User::create($data);
            $allow_system_roles = $this->user->hasRole('superadmin') ? true : false;
            $user->setRoles(Input::get('roles'), $allow_system_roles);
        } catch (ValidationException $e) {
            return Redirect::back()->withInput(Input::all())->withErrors($e->getErrors());
        }

        return Redirect::route('admin.users.index')->with('success', 'Successfully created User ' . Input::get('username'));

    }


    /**
     * Display the specified user.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);

        return View::make('admin_users.show', compact('user'));
    }


    /**
     * Show the form for editing the specified user.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $instances = Instance::all();
        $roles = $this->user->hasRole('superadmin') ? Role::all() : Role::instance()->get();

        return View::make('admin_users.edit', compact('user', 'instances', 'roles'));
    }


    /**
     * Update the specified user in storage.
     *
     * @param  int $id
     * @return Response
     */
    public function update($id)
    {
        $user = User::findOrFail($id);
        try {
            $data = Input::except('roles');
            if ( ! $data['password']) unset($data['password']);
            $user->update($data);
            $allow_system_roles = $this->user->hasRole('superadmin') ? true : false;
            $user->setRoles(Input::get('roles'), $allow_system_roles);
        } catch (ValidationException $e) {
            return Redirect::back()->withInput(Input::all())->withErrors($e->getErrors());
        }

        return Redirect::route('admin.users.index')->with('success', 'Successfully updated User ' . Input::get('username'));

    }


    /**
     * Remove the specified user from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        User::destroy($id);

        return Redirect::route('admin_users.index');
    }

}

app/views/admin_users/_form.blade.php
<div class="one field">
    <div class="field @if($errors->has('username')) error @endif">
        {{ Form::label('username', 'Username', array('class' => 'ui label')) }}
        <div class="ui left labeled input">
            {{ Form::text('username') }}
            <div class="ui corner label">
                <i class="icon asterisk"></i>
            </div>
        </div>
    </div>

    <div class="field @if($errors->has('password')) error @endif">
        {{ Form::label('password', 'Password', array('class' => 'ui label')) }}
        <div class="ui left labeled password input">
            {{ Form::password('password') }}
            <div class="ui corner label">
                <i class="icon lock"></i>
            </div>
        </div>
    </div>

    <div class="field @if($errors->has('password_confirmation')) error @endif">
        {{ Form::label('password_confirmation', 'Password confirmation', array('class' => 'ui label')) }}
        <div class="ui left labeled password input">
            {{ Form::password('password_confirmation') }}
            <div class="ui corner label">
                <i class="icon lock"></i>
            </div>
        </div>
    </div>

    <!-- Company -->
    <div class="field @if($errors->has('instance_id')) error @endif">
        {{ Form::label('instance_id', 'Instance', array('class' => 'ui label')) }}
        <div class="ui left labeled input">
            <div class="ui selection dropdown">
              <input type="hidden" name="instance_id" value="{{ $user->instance_id or Input::old('instance_id') }}">
              <div class="default text">Select Company</div>
              <i class="dropdown icon"></i>
              <div class="menu">
                @foreach ($instances as $instance)
                    <div class="item" data-value="{{ $instance->id }}">{{ $instance->title }}</div>
                @endforeach
              </div>
                <div class="ui corner label">
                    <i class="icon asterisk"></i>
                </div>
            </div>
        </div>
    </div>

    @if (isset($roles))
        <div class="field">
            {{ Form::label('roles', 'Roles', array('class' => 'ui label')) }}
            @foreach($roles as $role)
                <div class="field">
                    <div class="ui checkbox">
                      <input id="role_{{ $role->id }}" type="checkbox" name="roles[]" value="{{ $role->id }}"@if((isset($user) && $user->roles->contains($role)) || Input::get("roles.{$role->id}")) checked @endif>
                      <label for="role_{{ $role->id }}">{{ $role->title }}</label>
                    </div>
                </div>
            @endforeach
        </div>
    @endif

</div>

app/views/admin_users/create.blade.php
@extends('layouts.default')
@section('content')
<div class="sixteen wide column">

    <h1 class="ui header">Create User</h1>

    <div class="ui form segment">
        {{ Form::open(array('route' => array('admin.users.store'))) }}
        @include('admin_users._form')
        <button class="ui teal submit primary button">Create</button>
        {{ Form::close() }}
    </div>
</div>
@stop

app/views/admin_users/edit.blade.php
@extends('layouts.default')
@section('content')
<div class="sixteen wide column">

    <h1 class="ui header">Edit User Data</h1>

    <div class="ui form segment">
        {{ Form::model($user, array('method' => 'PUT', 'route' => array('admin.users.update', $user->id))) }}
        @include('admin_users._form')
        <button class="ui teal submit primary button">Update</button>
        {{ Form::close() }}
    </div>
</div>
@stop

app/views/admin_users/index.blade.php
@extends('layouts.default')
@section('content')
<div class="sixteen wide column">
<h1 class="ui header">Users</h1>
    <table class="ui sortable table segment">
        <thead>
            <tr>
                <th class="ascending">Username</th>
                <th>Instance</th>
                <th>Role(s)</th>
                <th class="actions">Actions</th>
            </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                <td>{{ $user->username }}</td>
                <td><?= ($user->instance) ? $user->instance->title : ''; ?></td>
                <td>{{ $user->roles->implode('title', ', ') }}</td>
                <td class="actions">
                    <a href="{{ route('admin.users.edit', array($user->id)) }}" class="ui mini icon button"><i class="icon edit"></i></a>
                    {{--<a href="{{ route('admin.users.destroy', array($user->id)) }}" class="ui mini button icon red"><i class="icon trash"></i></a>--}}
                </td>
            </tr>
        @endforeach
        </tbody>
        <tfoot>
        <tr>
            <th colspan="4">
                <a class="ui teal labeled icon mini button" href="{{ route('admin.users.create') }}">
                    <i class="plus icon"></i>
                    Add User
                </a>
            </th>
        </tr>
        </tfoot>
    </table>
</div>
@stop

app/views/admin_users/show.blade.php
/Applications/MAMP/htdocs/webeng-fs14/app/views/users/show.blade.php